# Generated by Django 5.1.3 on 2024-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
